version: "3.7"
services: 
  hugo-server:
    container_name: "report_site_creator"
    build: .
    ports: 
     - "1313:1313"
    command: sh -c "
      git clone https://github.com/L-TheG/trivyReportToHugoMd.git 
      && cd /trivyReportToHugoMd
      && git clone --recursive https://github.com/L-TheG/trivySecurityDocs.git
      && ln -s /report/report.json /trivyReportToHugoMd/report.json
      && npm install
      && npm run build
      && mkdir /trivyReportToHugoMd/trivySecurityDocs/content
      && node ./build/index.js --outDir=/trivyReportToHugoMd/trivySecurityDocs/content --severity=CRITICAL
      && cd trivySecurityDocs
      && /hugo -d /content"
    volumes:
      - .:/report
      - ./content:/content
