version: "3.7"
services: 
  hugo-server:
    build: .
    ports: 
     - "1313:1313"
    command: sh -c "
      git clone https://github.com/L-TheG/trivyReportToHugoMd.git 
      && cd /trivyReportToHugoMd
      && git clone --recursive https://github.com/L-TheG/trivySecurityDocs.git
      && ln -s /report/report.json /trivyReportToHugoMd/report.json
      && npm install --only=production
      && npm run build
      && node ./build/index.js outDir=/trivyReportToHugoMd/trivySecurityDocs/content
      && cd trivySecurityDocs
      && /hugo server --bind 0.0.0.0"
    volumes:
      - .:/report
